/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project1;

import java.awt.HeadlessException;
import java.sql.Date;
import java.sql.SQLException;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JOptionPane;

/**
 *
 * @author Prince Millenio
 */
public class peminjaman extends javax.swing.JInternalFrame {

    /**
     * Creates new form peminjaman
     */
    public String idPegawai ;
    public String idBarang;
    public int stok;
    public peminjaman() {
        initComponents();
        
        
        
        
    }
    public static java.sql.Date getCurrentJavaSqlDate() {
    java.util.Date today = new java.util.Date();
    return new java.sql.Date(today.getTime());
  }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIdPeg = new javax.swing.JTextField();
        btnPeg = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        disDepan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        disBelakang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        disDepart = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        disDesc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        disStok = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtIdAss = new javax.swing.JTextField();
        btnAss = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtJumlah = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnProses = new javax.swing.JButton();

        jTextField5.setText("jTextField5");

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("ID Pegawai");

        btnPeg.setText("Cari");
        btnPeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama Depan");

        disDepan.setEditable(false);

        jLabel4.setText("Nama Belakang");

        disBelakang.setEditable(false);

        jLabel5.setText("Departemen");

        disDepart.setEditable(false);

        jLabel7.setText("Deskripsi");

        disDesc.setEditable(false);

        jLabel8.setText("Jumlah tersedia");

        disStok.setEditable(false);

        jLabel9.setText("ID Asset");

        btnAss.setText("Cari");
        btnAss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel1.setText("Peminjaman");

        jLabel6.setText("Jumlah:");

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnPeg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtIdPeg, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                                        .addGap(70, 70, 70)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(disDepan, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                            .addComponent(disBelakang)
                                            .addComponent(disDepart)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(62, 62, 62)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnAss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtIdAss, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(69, 69, 69)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(disDesc)
                                            .addComponent(disStok, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 125, Short.MAX_VALUE))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(283, 283, 283)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(btnProses))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addComponent(jLabel6)
                                .addGap(39, 39, 39)
                                .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIdPeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPeg)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3))
                            .addComponent(disDepan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(disBelakang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(disDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(disDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(disStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdAss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAss)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnProses)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegActionPerformed
        // TODO add your handling code here:
        idPegawai = txtIdPeg.getText();
       
        if(txtIdPeg.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Masukkan Id Pegawai terlebih dahulu",
      "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            try { //
            java.sql.Connection conn = (java.sql.Connection)Project1.connection.koneksiDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet pegawai = stm.executeQuery("select * from pegawai where id_pegawai='"+ idPegawai +"'");
            if(pegawai.next()){
                String depan = pegawai.getString("nama_depan");
                disDepan.setText(depan);
                String belakang = pegawai.getString("nama_belakang");
                disBelakang.setText(belakang);
                String dep = pegawai.getString("departemen");
                disDepart.setText(dep);
                
            }
            
        } catch (SQLException | HeadlessException e) {}
        }
            
        
        
    }//GEN-LAST:event_btnPegActionPerformed

    private void btnAssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssActionPerformed
        // TODO add your handling code here:
        idBarang = txtIdAss.getText();
        if(txtIdAss.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Masukkan Id Barang terlebih dahulu",
      "Error", JOptionPane.ERROR_MESSAGE);
        }else{
             try { //
            java.sql.Connection conn = (java.sql.Connection)Project1.connection.koneksiDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet barang = stm.executeQuery("select * from aset_it where id_aset='"+idBarang+"'");
            if(barang.next()){
                String depan = barang.getString("deskripsi");
                disDesc.setText(depan);
            }
            
            java.sql.ResultSet barang1 = stm.executeQuery("select * from aset_inventory_it where id_aset='"+idBarang+"'");
            if(barang1.next()){
                String stokB = barang1.getString("stok_barang");
                disStok.setText(stokB);
            }
            
            
        } catch (SQLException | HeadlessException e) {}
        
        stok = Integer.parseInt(disStok.getText());
        }
            
        
       
    }//GEN-LAST:event_btnAssActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        int jumlah = Integer.parseInt(txtJumlah.getText());
        int value = ThreadLocalRandom.current().nextInt(100, 1000);
        int kode = Integer.parseInt(idBarang+""+value);


        
        if(txtIdPeg.getText().isEmpty() && txtIdAss.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Masukkan Id Pegawai dan Barang terlebih dahulu",
      "Error", JOptionPane.ERROR_MESSAGE);
        }else{ if(stok < jumlah){
            JOptionPane.showMessageDialog(null, "Stok barang tidak mencukupi",
      "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            int total = stok - jumlah;
        
        
        try {
                java.sql.Date date = getCurrentJavaSqlDate();
                String sql = "insert into aset_pegawai values('"+kode+"','"+idBarang+"','"+idPegawai+"','"+date+"','"+jumlah+"',null)";
                java.sql.Connection conn = (java.sql.Connection)Project1.connection.koneksiDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "berhasil diproses");
                JOptionPane.showMessageDialog(null, "Kode pengembalian anda adalah: "+kode);
                
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        
        try {
                String sql = "update aset_inventory_it SET stok_barang='"+total+"' where id_aset='"+idBarang+"'";
                java.sql.Connection conn = (java.sql.Connection)Project1.connection.koneksiDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        txtIdAss.setText("");
        txtIdPeg.setText("");
        txtJumlah.setText("");
        disBelakang.setText("");
        disDepan.setText("");
        disDepart.setText("");
        disDesc.setText("");
        disStok.setText(""); 
        }
        
        }
            
        
        
        
        
        
//        txtSisa.setText(total+"");
        
    }//GEN-LAST:event_btnProsesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAss;
    private javax.swing.JButton btnPeg;
    private javax.swing.JButton btnProses;
    private javax.swing.JTextField disBelakang;
    private javax.swing.JTextField disDepan;
    private javax.swing.JTextField disDepart;
    private javax.swing.JTextField disDesc;
    private javax.swing.JTextField disStok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField txtIdAss;
    private javax.swing.JTextField txtIdPeg;
    private javax.swing.JTextField txtJumlah;
    // End of variables declaration//GEN-END:variables

    

}
