/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project1;

import static Project1.peminjaman.getCurrentJavaSqlDate;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Prince Millenio
 */
public class pengembalian extends javax.swing.JInternalFrame {

    /**
     * Creates new form pengembalian
     */
    public pengembalian() {
        initComponents();
    }
    public String kode;
    public int jumlahBarang;
    public String asetBarang;
    public int stokBarangPub;
    
    private static java.sql.Date getCurrentJavaSqlDate() {
        java.util.Date today = new java.util.Date();
        return new java.sql.Date(today.getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        disJumlah = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        disNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        disBarang = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        disJumlah.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel1.setText("Pengembalian");

        jLabel2.setText("Kode");

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama Depan");

        disNama.setEditable(false);

        jLabel4.setText("Barang");

        disBarang.setEditable(false);

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        jLabel5.setText("jumlah");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtKode, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(disNama, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(disBarang)
                            .addComponent(disJumlah))
                        .addGap(0, 167, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(btnProses, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCari)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3))
                            .addComponent(disNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(disBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(disJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProses)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        kode = txtKode.getText();
        String aset="";
        String pegawai = "";
//        jumlah = Integer.parseInt(disJumlah.getText());
        
        try { //
            java.sql.Connection conn = (java.sql.Connection)Project1.connection.koneksiDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet barang = stm.executeQuery("select * from aset_pegawai where kode_pinjam='"+kode+"'");
            if(barang.next()){
                aset = barang.getString("id_aset");
                pegawai = barang.getString("id_pegawai");
                int jumlah = Integer.parseInt(barang.getString("jumlah"));
                disJumlah.setText(jumlah+"");
                
            }
            asetBarang = aset;
            jumlahBarang = Integer.parseInt(disJumlah.getText());
            
            java.sql.ResultSet idAset = stm.executeQuery("select * from aset_it where id_aset='"+aset+"'");
            if(idAset.next()){
                String a = idAset.getString("deskripsi");
                disBarang.setText(a);
            }
            
            java.sql.ResultSet idPeg = stm.executeQuery("select * from pegawai where id_pegawai='"+pegawai+"'");
            if(idPeg.next()){
                String b = idPeg.getString("nama_depan");
                disNama.setText(b);
            }
            
            
        } catch (SQLException | HeadlessException e) {}
        
        

    }//GEN-LAST:event_btnCariActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:

        try { //
            java.sql.Date date = getCurrentJavaSqlDate();
                String sql = "update aset_pegawai SET tanggal_kembali='"+date+"' where kode_pinjam='"+kode+"'";
                java.sql.Connection conn = (java.sql.Connection)Project1.connection.koneksiDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "berhasil diproses");
                
                
        } catch (SQLException | HeadlessException e) {}
        try { //
            java.sql.Connection conn = (java.sql.Connection)Project1.connection.koneksiDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet barang = stm.executeQuery("select * from aset_inventory_it where id_aset='"+asetBarang+"'");
            if(barang.next()){
                String a = barang.getString("stok_barang");
                int stokBarang =Integer.parseInt(a);
                stokBarangPub = stokBarang;
            }
            
        } catch (SQLException | HeadlessException e) {}
        
        int total = stokBarangPub + jumlahBarang;
        try {
                String sql = "update aset_inventory_it SET stok_barang='"+total+"' where id_aset='"+asetBarang+"'";
                java.sql.Connection conn = (java.sql.Connection)Project1.connection.koneksiDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, e);
            }
                System.out.println(stokBarangPub);
        
        
        disNama.setText("");
        disBarang.setText("");
        disJumlah.setText("");
        txtKode.setText("");
    }//GEN-LAST:event_btnProsesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnProses;
    private javax.swing.JTextField disBarang;
    private javax.swing.JTextField disJumlah;
    private javax.swing.JTextField disNama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtKode;
    // End of variables declaration//GEN-END:variables
}
